# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtree < Formula
  desc "Display Jaeger traces as a hierarchical tree in your terminal"
  homepage "https://github.com/tomarrell/jtree"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomarrell/jtree/releases/download/v0.1.1/jtree_0.1.1_darwin_amd64.tar.gz"
      sha256 "ec5ad0e801850e3012710f2ef806e31af697caa45c5225538c382289feeb8085"

      def install
        bin.install "jtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomarrell/jtree/releases/download/v0.1.1/jtree_0.1.1_darwin_arm64.tar.gz"
      sha256 "6fe4a03f9e0a355c5894e0464f51ace30d4186035ddd582f46411874ec8ae29d"

      def install
        bin.install "jtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomarrell/jtree/releases/download/v0.1.1/jtree_0.1.1_linux_amd64.tar.gz"
      sha256 "985258105b403f290d1924834f359b1a31ab97b1cb9736d13cc3c20fa1a5b615"
      def install
        bin.install "jtree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomarrell/jtree/releases/download/v0.1.1/jtree_0.1.1_linux_arm64.tar.gz"
      sha256 "a0089b4631b630a0617c5d4f3d586a21d5f349070fd069c14cb96aa039abd729"
      def install
        bin.install "jtree"
      end
    end
  end

  test do
    system "#{bin}/jtree", "-h"
  end
end
